Added-Employee-Information-Management-System
RoCS2024/employee-information-management pull request #10
Opened 2024-03-04 14:30 UTC by WyteRichard

2024-03-05 09:46 UTC, RoCS2024 requested changes
change the name of the packages, check with Con how to do it

2024-03-06 13:05 UTC, RoCS2024 commented on employee-information-management-system/build.xml
> +<project name="Ant Test Project" default="build">
fix the name of the project

2024-03-06 13:05 UTC, RoCS2024 approved these changes

2024-03-06 13:06 UTC, esdi-00 approved these changes

2024-03-06 13:08 UTC, merged