Added Update Employee
RoCS2024/employee-information-management pull request #14
Opened 2024-03-08 05:40 UTC by daiahnadine

2024-03-08 11:45 UTC, esdi-00 commented on employee-information-management-system/src/main/java/com/employee/information/management/app/facade/employee/impl/EmployeeFacadeImpl.java
>  public class EmployeeFacadeImpl {
This does not implement EmployeeFacade

2024-03-08 11:46 UTC, esdi-00 commented on employee-information-management-system/src/main/java/com/employee/information/management/data/employee/dao/impl/EmployeeDaoImpl.java
>  public class EmployeeDaoImpl {
This does not implement EmployeeDao

2024-03-08 11:46 UTC, esdi-00 requested changes
see comments

2024-03-11 00:19 UTC, daiahnadine commented on employee-information-management-system/src/main/java/com/employee/information/management/data/employee/dao/impl/EmployeeDaoImpl.java
>  public class EmployeeDaoImpl {
Noted po, Sir. Thank you po.

2024-03-12 13:05 UTC, RoCS2024 commented on employee-information-management-system/src/main/java/Main.java
> +<<<<<<< Updated upstream
why do you have stashed changes here?

2024-03-12 13:05 UTC, RoCS2024 commented on employee-information-management-system/src/main/java/com/employee/information/management/app/facade/employee/EmployeeFacade.java
> +<<<<<<< Updated upstream
Another stashed changes here

2024-03-12 13:05 UTC, RoCS2024 commented on employee-information-management-system/src/main/java/com/employee/information/management/app/facade/employee/impl/EmployeeFacadeImpl.java
> +<<<<<<< Updated upstream
Another one

2024-03-12 13:06 UTC, RoCS2024 requested changes
Please clean the codes. Remove the stashes

2024-03-13 12:53 UTC, RoCS2024 commented on employee-information-management-system/src/main/java/com/employee/information/management/app/facade/employee/impl/EmployeeFacadeImpl.java
> +    public List<Employee> getAllEmployees() throws RuntimeException {
why is this returning null?

2024-03-13 12:53 UTC, RoCS2024 commented on employee-information-management-system/src/main/java/com/employee/information/management/data/employee/dao/impl/EmployeeDaoImpl.java
> +    public List<Employee> getAllEmployee() {
why does this return null?

2024-03-13 12:53 UTC, RoCS2024 requested changes
see comments

2024-03-13 13:10 UTC, closed without merging